apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: gopalbugad/inventory:latest
        ports:
        - containerPort: 8082
      env:
      - name: ESPRESSO_SHOT_QUANTITY
        valueFrom: 
          ConfigMapKeyRef:
            name: dev-configmap
            key: ESPRESSO_SHOT_QUANTITY
      - name: MILK_QUANTITY
        valueFrom:
          ConfigMapKeyRef:
            name: dev-configmap
            key: MILK_QUANTITY
