apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-inventory-deployment
  labels:
    app: inventory
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: gopalbugad/inventory:latest
        ports:
        - containerPort: 8082
        env:
        - name: ESPRESSO_SHOT_QUANTITY
          valueFrom: 
            configMapKeyRef:
              name: dev-inv-config
              key: ESPRESSO_SHOT_QUANTITY
        - name: MILK_FOAM_QUANTITY
          valueFrom:
            configMapKeyRef:
              name: dev-inv-cm
              key: MILK_FOAM_QUANTITY
  selector:
    matchLabels:
      app: inventory
