apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: gopalbugad/inventory:latest
        ports:
        - containerPort: 8082
        env:
        - name: ESPRESSO_SHOT_QUANTITY
          valueFrom: 
            configMapKeyRef:
              name: dev-inv-cm
              key: ESPRESSO_SHOT_QUANTITY
        - name: MILK_QUANTITY
          valueFrom:
            configMapKeyRef:
              name: dev-inv-cm
              key: MILK_QUANTITY
