apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: gopalbugad/order:latest
        ports:
        - containerPort: 8083
        env:
        - name: INVENTORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ord-config
              key: INVENTORY_SERVICE_URL
        resources:
          requests:
            cpu: "10m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "1000Mi"
  selector:
    matchLabels:
      app: order